from dataclasses import dataclass
from typing import Optional
import numpy as np

@dataclass
class VehicleObservation:
    """Inputs required by the 3D Dimension Estimator."""
    vehicle_id: int
    image_crop: np.ndarray        # RGB crop of the vehicle from the main frame
    bounding_box_2d: tuple        # (x1, y1, x2, y2)
    geometric_distance_m: float   # Trusted distance from Phase 2C.1
    geometric_heading_deg: float  # Trusted heading from Phase 2C.1
    class_id: int                 # Vehicle class (e.g., car, truck)


@dataclass
class DimensionEstimate:
    """Outputs generated by the 3D Dimension Estimator."""
    width_m: float
    length_m: float
    height_m: float
    confidence: float             # 0.0 to 1.0
    orientation_offset_deg: float # Optional refinement delta to geometric heading


@dataclass
class FinalVehicleFootprint:
    """The final merged output for downstream planning."""
    vehicle_id: int
    center_x_m: float
    center_y_m: float
    distance_m: float
    heading_deg: float
    width_m: float
    length_m: float
    height_m: float
    is_learned_dimension: bool    # True if from network, False if fallback geometry


class VehicleDimensionEstimator:
    """Base interface for all plug-and-play 3D dimension networks."""
    
    def __init__(self, model_path: str, **kwargs):
        pass

    def estimate_dimensions(self, obs: VehicleObservation) -> DimensionEstimate:
        """
        Must be implemented by child classes (e.g., SMOKE, RTM3D).
        """
        raise NotImplementedError("Model implementation required.")


class DummyGeometryFallback(VehicleDimensionEstimator):
    """
    Fallback estimator that returns heuristic physical dimensions 
    when no deep learning model is active.
    """
    def estimate_dimensions(self, obs: VehicleObservation) -> DimensionEstimate:
        # Hardcoded safe priors for passenger vehicles
        return DimensionEstimate(
            width_m=1.8,
            length_m=4.5,
            height_m=1.5,
            confidence=0.1,
            orientation_offset_deg=0.0
        )
